DISTRO_FEEDS_PREFIX = "http://familiar.handhelds.org/releases/${DISTRO_VERSION}"

DISTRO_FEEDS_COLLECTIONS = "feed universe"
DISTRO_FEEDS_COLLECTION_DESC_feed = "Familiar ${DISTRO_VERSION} feeds"
DISTRO_FEEDS_COLLECTION_DESC_universe = "Familiar ${DISTRO_VERSION} universe feeds"

# opie and gpe images append to this
DISTRO_FEEDS_IN_feed = "base updates common"
DISTRO_FEEDS_IN_universe = "common"

DISTRO_FEEDS_FEED_DESC_base = "essential packages"
DISTRO_FEEDS_FEED_DESC_updates = "security updates"
DISTRO_FEEDS_FEED_DESC_common = "additional packages not specific to any graphical environment"
DISTRO_FEEDS_FEED_DESC_x11 = "additional packages specific to the x11 graphical environment"
DISTRO_FEEDS_FEED_DESC_opie = "additional packages specific to the opie graphical environment"

